version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: whmcsdb
    restart: unless-stopped
    hostname: mysql
    networks:
      whmcs:
        ipv4_address: 172.18.18.2
    environment:
      MYSQL_ROOT_PASSWORD: "pw123123"
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3332:3306

  whmcs:
    image: fauzie/docker-whmcs:latest
    container_name: "WHMCS"
    hostname: whmcs
    networks:
      whmcs:
        ipv4_address: 172.18.18.3
    restart: always
    depends_on:
      - mysql
    environment:
      WORKER_PROCESSES: 4
      VIRTUAL_HOST: whmcs.test
      APP_PASSWORD: userapppassword
      WHMCS_SERVER_IP: 172.18.18.1
      HTTPS: "on"
    ports:
      - 8883:80
      - 8822:22
    volumes:
      - /home/www/whmcs:/var/www/whmcs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pmawhmcs
    hostname: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: unless-stopped
    networks:
      whmcs:
        ipv4_address: 172.18.18.4
    ports:
      - 8884:80

networks:
  whmcs:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.18.0/29
          gateway: 172.18.18.1